version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: glpi_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Cloud*Mega*2026
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=phcadmin
      - MYSQL_PASSWORD=Cloud*Mega*2026
    volumes:
      - db_data:/var/lib/mysql

  glpi:
    image: elestio/glpi:latest
    container_name: glpi_app
    restart: always
    ports:
      - "80:80"
    environment:
      - TIMEZONE=Africa/Maputo
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 512M
    volumes:
      - glpi_data:/var/www/html/glpi/files
      - glpi_config:/var/www/html/glpi/config

volumes:
  glpi_data:
  glpi_config:
  db_data:
